name: client
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.7
  get: ^4.6.6
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  http: ^0.13.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  animated_text_kit: ^4.2.2
  google_sign_in: ^6.1.4
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.3.0
  intl: ^0.17.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  flutter_facebook_auth: ^5.0.11
  shared_preferences: ^2.2.2
  share_plus: ^7.1.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.2.19
  intl_phone_number_input: ^0.7.3+1
  dotted_border: ^2.0.0+3
  image_cropper_platform_interface: ^4.0.0
  image_cropper: ^4.0.1
  flutter_dotenv: ^5.1.0
  dartz: ^0.10.1
  path_provider: ^2.0.13
  multi_image_picker_view: ^0.0.15
  flutter_screenutil: ^5.9.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  animated_bottom_navigation_bar: ^1.3.3
  flutter_stripe: ^10.2.0
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - .env
  fonts:
    - family: Times
      fonts:
        - asset: fonts/Times/times new roman.ttf
          weight: 300
        - asset: fonts/Times/times new roman bold.ttf
          weight: 800
